//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by SpCutter.rc
//
#define IDD_ABOUTBOX                    100
#define IDP_SOCKETS_INIT_FAILED         104
#define IDR_MAINFRAME                   128
#define IDR_CUTPLOTYPE                  129
#define IDDLG_DISP                      131
#define IDDLG_KB                        132
#define IDDLG_MAN_CTRL                  133
#define IDDLG_PROTECTPARA               134
#define IDDLG_REG                       135
#define IDDLG_SET_MAC                   136
#define IDDLG_SET_SOFT                  137
#define IDDLG_REG_SN                    138
#define IDDLG_SUPER_USER                139
#define IDR_MENU_PARA_DEF               140
#define IDDLG_ABOUTGM                   140
#define IDR_POPMENU_LIST                150
#define IDR_POPMENU_VIEW                151
#define IDR_FON_HZ                      180
#define IDR_FON_EN                      181
#define IDDLG_BAR                       183
#define IDCHK_SP1                       201
#define IDCHK_SP2                       202
#define IDCHK_AUTO_WORK                 203
#define IDCHK_CONFIRM_FIRST_PAGE        204
#define IDCHK_DISPLAY_DIR               205
#define IDCHK_DISPLAY_NUM               206
#define IDCHK_AUTO_PAUSE                207
#define IDCHK_AUTO_DEL_PLT              208
#define IDCHK_DISPLIST_LEFT             209
#define IDCHK_AUTO_CLEANSP              210
#define IDCHK_BIDIR                     211
#define IDCHK_PUMPON                    212
#define IDCHK_CUT_DOWN                  213
#define IDCB_INPUT_REGCODE              1000
#define IDCB_CLR_PEN                    1001
#define IDCB_CLR_BLADE                  1002
#define IDCB_CLR_DEFAULT                1003
#define IDCB_CLR_BG                     1004
#define IDCB_CLR_FR                     1005
#define IDCB_BAK_ORG                    1006
#define IDCB_PROTECT_PARA               1007
#define IDCB_CONFIRM                    1008
#define IDCB_PARA_SAVE                  1009
#define IDCB_PARA_RESTORE               1010
#define IDCB_SET_AUTO_DIR               1011
#define IDCB_PLT_OPEN                   1020
#define IDCB_PLT_ADD                    1021
#define IDCB_PLT_SAVE                   1022
#define IDCB_PARA_SET                   1023
#define IDCB_V_SEL                      1024
#define IDCB_V_MOVE                     1025
#define IDCB_SP_CLEAN                   1026
#define IDCB_ZOOM_IN                    1027
#define IDCB_ZOOM_OUT                   1028
#define IDCB_ZOOM_ALL                   1029
#define IDCB_WORK_START                 1030
#define IDCB_WORK_CANCEL                1032
#define ID_APP_TO_TRAY                  1033
#define IDCB_MANUAL_CTRL                1034
#define IDCB_PARA_DEFAULT               1040
#define IDCB_SET_ZP                     1041
#define IDCE_END_DATE                   1042
#define IDCE_PASSWORD                   1043
#define IDCE_ENDPOS_X                   1044
#define IDCE_ENDPOS_Y                   1045
#define IDCMB_END_POS                   1046
#define IDCE_AUTH_CODE                  1047
#define IDCE_AUTH_SN                    1048
#define IDCE_PLT_SCALE                  1049
#define IDCE_SN                         1050
#define IDCE_CODE                       1051
#define IDTXT_RAND_CODE                 1052
#define IDCE_RANDPW                     1053
#define IDCEP_PW                        1060
#define IDCEP_PPMM_X                    1061
#define IDCEP_PPMM_Y                    1062
#define IDCEP_MACSIZE_X                 1063
#define IDCEP_MACSIZE_Y                 1064
#define IDCEP_ACCSTEP                   1065
#define IDCEP_SPD_CUT                   1066
#define IDCEP_SPD_MOVE                  1067
#define IDCE_DISP_SIZEX                 1100
#define IDCE_DISP_SIZEY                 1101
#define IDCE_K_PWM                      1102
#define IDCE_ANGLE_ADJUST               1103
#define IDCE_CUTPAPER_LEN               1104
#define IDC_EDIT_PW                     1105
#define IDC_URL                         1106
#define IDCB_SYS_RESET                  1107
#define IDCE_OVERCUT_LEN                1108
#define IDCE_KVOLT_START                1109
#define IDCE_KVOLT_WORK                 1110
#define IDCHK_JAMDETEC                  1111
#define IDCB_WORK_PAUSE                 1112
#define IDCE_10000X                     1113
#define IDCE_10000Y                     1114
#define IDCE_SPD_PLOT                   1115
#define IDCE_KPX                        1116
#define IDCB_WORK_RESUME                1117
#define IDCE_KPY                        1118
#define IDCE_SPDDY                      1119
#define IDCE_AUTO_CUT_LEN               1120
#define IDCE_LINE_WIDTH                 1121
#define IDCB_YP                         1122
#define IDCE_SPEX                       1123
#define IDCB_STOP                       1124
#define IDCE_SP12EY                     1125
#define IDCB_YN                         1126
#define IDCB_XN                         1127
#define IDCE_LED_LAN                    1128
#define IDCB_XP                         1129
#define IDCHK_IG_BLANK_LEFT             1130
#define IDCHK_IG_BLANK_BOTTOM           1131
#define IDC_WEBSITE                     1132
#define IDCE_SP_LRDOT1                  1133
#define IDCE_SP_LRDOT2                  1134
#define IDCHK_ONLYPLOT                  1135
#define IDCE_PLT_SEC_LEN                1136
#define IDCE_CURVE_LEN                  1137
#define IDCE_BLANK_MM                   1138
#define IDCB_APPLY_BLANK_MM             1139
#define IDCEP_SD_PERCENT                1153
#define IDCE_XSCALE                     1155
#define IDCE_YSCALE                     1156
#define IDCHK_SEARCHOUTLINE             1157
#define IDC_COMBO_SP_TYPE               1159
#define IDTXT_PW                        1200
#define IDTXT_REGINFO                   1201
#define IDTXT_START_TIME                1202
#define IDTXT_END_TIME                  1203
#define IDTXT_DATADIR                   1204
#define IDC_TXT1                        1205
#define IDC_TXT2                        1206
#define IDC_TXT3                        1207
#define IDC_TXT_PW                      1208
#define IDC_PTXT1                       1209
#define IDC_PTXT2                       1210
#define IDC_PTXT3                       1211
#define IDC_PTXT4                       1212
#define IDC_PTXT5                       1213
#define IDC_PTXT6                       1214
#define IDC_PTXT7                       1215
#define IDC_PTXT8                       1216
#define IDC_PTXT9                       1217
#define ID_FILE_ATF_30x30               32700
#define ID_FILE_ATF_10x10               32701
#define ID_FILE_ATF_20x20               32702
#define ID_FILE_ATF_40x40               32703
#define ID_FILE_ATF_50x50               32704
#define IDM_SET_DISP                    32710
#define IDM_SET_DIR                     32711
#define IDM_LIST_DEL                    32712
#define IDM_LIST_CLEAN                  32713
#define IDM_TO_PEN                      32714
#define IDM_TO_CUT                      32715
#define IDM_DEL_CURVE                   32716
#define IDM_CHANGE_DIR                  32717
#define IDM_DEL_PLOT_DATA               32720
#define IDM_DEL_CUT_DATA                32721
#define IDM_ALL_TO_CUT                  32722
#define IDM_ALL_TO_PLOT                 32723
#define IDS_SYS_STATE                   32800
#define IDS_PROGRESS                    32801
#define IDM_AUTH_INFO                   32810
#define IDM_LIST_TOP                    32811
#define IDM_SUPER_USER                  32812
#define IDM_1209                        32820
#define IDM_1509                        32821
#define IDM_1512                        32822
#define IDM_1510                        32823
#define IDM_LAN_CHS                     32838
#define IDM_LAN_CHT                     32839
#define IDM_LAN_EN                      32840
#define IDM_BREAK_CURVE                 32841

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_3D_CONTROLS                     1
#define _APS_NEXT_RESOURCE_VALUE        184
#define _APS_NEXT_COMMAND_VALUE         32842
#define _APS_NEXT_CONTROL_VALUE         1160
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
