//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ 生成的包含文件。
// 供 Dll_EN.rc 使用
//
#define IDD_ABOUTBOX                    100
#define IDP_SOCKETS_INIT_FAILED         104
#define IDR_MAINFRAME                   128
#define IDR_CUTPLOTYPE                  129
#define IDDLG_DISP                      131
#define IDDLG_PROTECTPARA               132
#define IDDLG_REG                       133
#define IDDLG_PARA                      134
#define IDDLG_SET_SOFT                  135
#define IDDLG_REG_SN                    136
#define IDDLG_SUPER_USER                137
#define IDDLG_ABOUTGM                   138
#define IDDLG_BAR                       139
#define IDR_MENU_PARA_DEF               150
#define IDR_POPMENU_LIST                151
#define IDR_POPMENU_VIEW                152
#define IDR_FON_HZ                      153
#define IDR_FON_EN                      154
#define IDI_AR_DOWN                     180
#define IDI_AR_LEFT                     181
#define IDI_AR_RIGHT                    182
#define IDI_AR_UP                       183
#define IDI_WSPCLEAN                    191
#define IDI_WCANCEL                     192
#define IDI_WPAUSE                      193
#define IDI_WSTART                      194
#define IDI_ZP_SET                      196
#define IDI_ZP_TO_DEF                   197
#define IDCHK_SP1                       201
#define IDCHK_SP2                       202
#define IDCHK_CONFIRM_FIRST_PAGE        203
#define IDCHK_DISPLAY_DIR               204
#define IDCHK_DISPLAY_NUM               205
#define IDCHK_AUTO_PAUSE                206
#define IDCHK_AUTO_DEL_PLT              207
#define IDCHK_AUTO_CLEANSP              208
#define IDCHK_BIDIR                     209
#define IDCHK_PUMPON                    210
#define IDCHK_CUT_DOWN                  211
#define IDDLG_PWD                       211
#define IDCHK_JAMDETEC                  212
#define IDCHK_IG_BLANK_LEFT             213
#define IDCHK_IG_BLANK_BOTTOM           214
#define IDCHK_SEARCHOUTLINE             215
#define IDCHK_CLEANSP                   216
#define IDCHK_ONLYPLOT                  217
#define IDCHK_JOB_AUTO_START            218
#define IDC_COMBO_SP_TYPE               219
#define IDCB_INPUT_REGCODE              300
#define IDCB_CLR_PEN                    301
#define IDCB_CLR_BLADE                  302
#define IDCB_CLR_DEFAULT                303
#define IDCB_CLR_BG                     304
#define IDCB_CLR_FR                     305
#define IDCB_TO_DEFZP                   306
#define IDCB_PROTECT_PARA               307
#define IDCB_CONFIRM                    308
#define IDCB_PARA_SAVE                  309
#define IDCB_PARA_RESTORE               310
#define IDCB_SET_AUTO_DIR               311
#define IDCB_PLT_OPEN                   312
#define IDCB_PLT_ADD                    313
#define IDCB_PLT_SAVE                   314
#define IDCB_PARA_SET                   315
#define IDCB_SPCLEAN                    316
#define IDCB_ZOOM_ALL                   317
#define IDCB_WORK_START                 318
#define IDCB_WORK_PAUSE                 319
#define IDCB_WORK_CANCEL                320
#define IDCB_APPLY_BLANK_MM             321
#define IDCB_CHANGE_RATE                322
#define IDCB_MANUAL_CTRL                323
#define IDCB_PARA_DEFAULT               324
#define IDCB_SET_ZP                     325
#define ID_APP_TO_TRAY                  326
#define IDCB_AR_UP                      327
#define IDCB_AR_DOWN                    328
#define IDCB_AR_LEFT                    329
#define IDCB_AR_RIGHT                   330
#define IDCB_DLG_BAR                    331
#define IDCMB_END_POS                   400
#define IDTXT_RAND_CODE                 500
#define IDC_URL                         501
#define IDC_WEBSITE                     502
#define IDCE_END_DATE                   600
#define IDCE_PASSWORD                   601
#define IDCE_ENDPOS_X                   602
#define IDCE_ENDPOS_Y                   603
#define IDCE_AUTH_CODE                  604
#define IDCE_AUTH_SN                    605
#define IDCE_PLT_SCALE                  606
#define IDCE_SN                         607
#define IDCE_CODE                       608
#define IDCE_RANDPW                     609
#define IDCE_DISP_SIZEX                 610
#define IDCE_DISP_SIZEY                 611
#define IDCE_ANGLE_ADJUST               612
#define IDCE_OVERCUT_LEN                613
#define IDCE_KVOLT_START                614
#define IDCE_KVOLT_WORK                 615
#define IDCE_10000X                     616
#define IDCE_10000Y                     617
#define IDCE_SPD_PLOT                   618
#define IDCE_KPX                        619
#define IDCE_KPY                        620
#define IDCE_SPDDY                      621
#define IDCE_CUT_PAPER_STSRT            622
#define IDCE_LINE_WIDTH                 623
#define IDCE_CUT_PAPER_END              624
#define IDCE_SPEX                       625
#define IDCE_SP12EY                     626
#define IDCE_LED_LAN                    627
#define IDCE_SP_LRDOT1                  628
#define IDCE_SP_LRDOT2                  629
#define IDCE_PLT_SEC_LEN                630
#define IDCE_CURVE_LEN                  631
#define IDCE_XSCALE                     632
#define IDCE_YSCALE                     633
#define IDCE_BLANKMM                    634
#define IDCEP_PW                        700
#define IDCEP_PPMM_X                    701
#define IDCEP_PPMM_Y                    702
#define IDCEP_MACSIZE_X                 703
#define IDCEP_MACSIZE_Y                 704
#define IDCEP_ACCMM                     705
#define IDCEP_SPD_CUT                   706
#define IDCEP_SPD_MOVE                  707
#define IDCEP_SEC_LEN                   708
#define IDCEP_CURVE_SPD                 709
#define IDTXT_PW                        1000
#define IDTXT_REGINFO                   1001
#define IDTXT_START_TIME                1002
#define IDTXT_END_TIME                  1003
#define IDTXT_DATADIR                   1004
#define IDC_TXT1                        1005
#define IDC_TXT2                        1006
#define IDC_TXT_PW                      1008
#define ID_TXT_MAC_STA                  1009
#define IDCE_PWD                        1123
#define IDTXT_PWD                       1205
#define ID_FILE_ATF_30x30               32700
#define ID_FILE_ATF_10x10               32701
#define ID_FILE_ATF_20x20               32702
#define ID_FILE_ATF_40x40               32703
#define ID_FILE_ATF_50x50               32704
#define IDM_SET_DISP                    32710
#define IDM_SET_DIR                     32711
#define IDM_LIST_DEL                    32712
#define IDM_LIST_CLEAN                  32713
#define IDM_TO_PEN                      32714
#define IDM_TO_CUT                      32715
#define IDM_DEL_CURVE                   32716
#define IDM_CHANGE_DIR                  32717
#define IDM_DEL_PLOT_DATA               32720
#define IDM_DEL_CUT_DATA                32721
#define IDM_ALL_TO_CUT                  32722
#define IDM_ALL_TO_PLOT                 32723
#define IDM_AUTH_INFO                   32800
#define IDM_LIST_TOP                    32801
#define IDM_SUPER_USER                  32802
#define IDM_1209                        32803
#define IDM_1509                        32804
#define IDM_1512                        32805
#define IDM_1510                        32806
#define IDM_LAN_CHS                     32807
#define IDM_LAN_CHT                     32808
#define IDM_LAN_EN                      32809
#define IDM_BREAK_CURVE                 32810
#define IDM_CONNECT_VIA_USB             32842
#define IDM_CONNECT_VIA_ETH             32843

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_3D_CONTROLS                     1
#define _APS_NEXT_RESOURCE_VALUE        190
#define _APS_NEXT_COMMAND_VALUE         32844
#define _APS_NEXT_CONTROL_VALUE         1146
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
